### ISSUE TITLE
You've got errors on your Github.io site

### ISSUE THREAD

**Issue by sancarn** [opal/opal-cdn#27] opened 2018-09-11 20:07 UTC
On http://cdn.opalrb.com/

I get an error in opal.min.js:

```
Uncaught RangeError: Maximum call stack size exceeded
    at module_constructor.method_missing_stub [as $method_missing] (opal.min.js:1)
    at module_constructor.method_missing_stub [as $method_missing] (opal.min.js:1)
    at module_constructor.method_missing_stub [as $method_missing] (opal.min.js:1)
    at module_constructor.method_missing_stub [as $method_missing] (opal.min.js:1)
    at module_constructor.method_missing_stub [as $method_missing] (opal.min.js:1)
    at module_constructor.method_missing_stub [as $method_missing] (opal.min.js:1)
    at module_constructor.method_missing_stub [as $method_missing] (opal.min.js:1)
    at module_constructor.method_missing_stub [as $method_missing] (opal.min.js:1)
    at module_constructor.method_missing_stub [as $method_missing] (opal.min.js:1)
    at module_constructor.method_missing_stub [as $method_missing] (opal.min.js:1)
```

I also get similar errors when loading `native`:

```
Opal.load('native')
opal.min.js:1 Uncaught RangeError: Maximum call stack size exceeded
    at module_constructor.method_missing_stub [as $method_missing] (opal.min.js:1)
    at module_constructor.method_missing_stub [as $method_missing] (opal.min.js:1)
    at module_constructor.method_missing_stub [as $method_missing] (opal.min.js:1)
    at module_constructor.method_missing_stub [as $method_missing] (opal.min.js:1)
    at module_constructor.method_missing_stub [as $method_missing] (opal.min.js:1)
    at module_constructor.method_missing_stub [as $method_missing] (opal.min.js:1)
    at module_constructor.method_missing_stub [as $method_missing] (opal.min.js:1)
    at module_constructor.method_missing_stub [as $method_missing] (opal.min.js:1)
    at module_constructor.method_missing_stub [as $method_missing] (opal.min.js:1)
    at module_constructor.method_missing_stub [as $method_missing] (opal.min.js:1)
```

And get other errors when loading `opal-parser`:

```
Opal.load("opal-parser")
opal.min.js:1 Uncaught TypeError: (cref || _Object).$const_missing is not a function
    at const_missing (opal.min.js:1)
    at Object.Opal.const_get_relative (opal.min.js:1)
    at opal-parser.min.js:1
    at Opal.modules.set (opal-parser.min.js:1)
    at Object.Opal.load (opal.min.js:1)
    at Object_alloc.Opal.require [as $require] (opal.min.js:1)
    at Opal.modules.opal/compiler (opal-parser.min.js:32)
    at Object.Opal.load (opal.min.js:1)
    at Object_alloc.Opal.require [as $require] (opal.min.js:1)
    at Opal.modules.opal-parser (opal-parser.min.js:32)
```

**Comment by ggrossetie** [comment] 2018-09-12 07:24
Hi @sancarn 

Which version are you using ? the latest ? `0.10.1` ? Could you please provide your HTML page or your Node script so we can reproduce this issue ?

Thanks

**Comment by sancarn** [comment] 2018-09-12 14:00
Apologies I included the wrong url:
https://opal.github.io/opal-cdn

It's the index.html of the opal-cdn project

**Comment by sancarn** [comment] 2018-09-12 14:02
Looking at your HTML it looks like you use the current version of opal

**Comment by ggrossetie** [comment] 2018-09-15 10:03
I'm not sure I quite understand... you should use `//cdn.opalrb.com/opal/0.10.1/opal.js`. If it's working feel free to close this issue 😉

**Comment by glebm** [comment] 2018-09-15 13:31
![opal-cdn](https://user-images.githubusercontent.com/216339/45586774-f9a98400-b8f3-11e8-9ddb-8c71a6e4f966.png)

**Comment by ggrossetie** [comment] 2018-09-15 14:07
Ahhh OK, now I see :+1: 
Indeed version 0.11.0 (current) or up (master) are "broken". I can reproduce both errors. I will investigate!

Thanks @sancarn & @glebm

**Comment by ggrossetie** [comment] 2018-09-15 14:35
This issue is fixed on master (ie. I can't reproduce it): https://github.com/opal/opal/commit/82f5c9708a0d53c284c44e6d302bf79cd09d70de but still present on the latest release: https://github.com/opal/opal/tree/v0.11.3

@elia Are you aware of this issue ? Can we release a new version and/or update the "master version" ?

**Comment by elia** [comment] 2018-09-17 19:39
@Mogztter (sorry for the delay) I wasn't aware of the issue, we should definitely open an issue on github.com/opal/opal/issues/new

**Comment by ggrossetie** [comment] 2018-09-17 20:25
No worries.
The issue seems to be resolved on master that's why I didn't open a new issue. However I don't know why it was broken nor how it was resolved.

**Comment by elia** [comment] 2018-09-29 13:57
Found it! it was missing an `Opal.load('opal')` 😅

**Closed as completed** 2018-09-29 13:56 UTC

**Comment by ggrossetie** [comment] 2018-09-29 14:06
Oh, I didn't think of that! 
Nice catch 😉
